default: &default
adapter: postgresql
encoding: unicode
pool: 5

development:
<<: *default
database: newname198_production
username: newname198
password: <%= ENV['NEWNAME198_DATABASE_PASSWORD'] %>

test:
<<: *default
database: PersonalTrainer_test

production:
<<: *default
database: newname198_production
username: newname198
password: <%= ENV['NEWNAME198_DATABASE_PASSWORD'] %>
