default: &default
adapter: postgresql
encoding: unicode
pool: 5

development:
<<: *default
database: PersonalTrainer_development

test:
<<: *default
database: PersonalTrainer_test

production:
<<: *default
database: PersonalTrainer_production
username: PersonalTrainer
password: <%= ENV['PERSONAL_TRAINER_DATABASE_PASSWORD'] %>